spring:
  data:
    mongodb:
#      authentication-database: admin
#      username: #your_root_user     (default->rootuser)
#      password: #your_root_password (default->rootpass)
      database: springDemo
#      port: #your_port              (default->27017)
#      host: #your_host              (default->localhost)